envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
ingress:
  rules:
  - component:
      name: bacs350-demo-app
    match:
      path:
        prefix: /
  - component:
      name: bacs350-demo-static
    match:
      path:
        prefix: /static
name: bacs350-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Andrewholmes22/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350-demo-app
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: student/05/notepad
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Andrewholmes22/PythonWebApps
  name: bacs350-demo-static
  source_dir: student/05/notepad/static
