# Generated by Django 4.2.4 on 2023-10-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='identity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
