envs:
- key: DJANGO_ALLOWED_HOSTS
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DEVELOPMENT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: profile-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350
  routes:
  - path: /
  run_command: |-
    python manage.py migrate
    gunicorn --worker-tmp-dir /dev/shm week1/ProfileApp/config.wsgi
  source_dir: /week1/ProfileApp
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  name: static
  routes:
  - path: /static
  source_dir: static