envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DEVELOPMENT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
name: hammerhead-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350-week-3-superhero
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    cd week3/Superhero
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: week3/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  name: bacs350-week-3-superhero-static
  routes:
  - path: /static
  source_dir: week3/Superhero/static
