alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: profile-app
    match:
      path:
        prefix: /
name: hammerhead-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  - key: DJANGO_ALLOWEDHOST
    scope: RUN_AND_BUILD_TIME
    value: .ondigitalocean.app
  - key: DEVELOPEMENT_MODE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  github:
    branch: main
    deploy_on_push: true
    repo: Andrewholmes22/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: profile-app
  run_command: |-
    Python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: 02/ProfileApp