name: bacs350-demo
region: nyc
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  name: bacs350-demo-static
  routes:
  - path: /
  source_dir: 12/CourseBuilder/Website
